image: ubuntu

build:
  stage: build
  script:
    - apt-get -qq update
    - apt-get -y install build-essential
    - apt-get -y install cmake
    - cd /builds/penasa/spc
    - mkdir build
    - cd build
    - cmake ../
    
