image: ubuntu



build:
  stage: build
  script:
    - apt-get -qq update
    - apt-get -y install build-essential cmake libeigen3-dev libboost-all-dev libgflags-dev git
    - cd /builds/penasa/spc
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ../
    - make -j 4
    
