image: ubuntu

before_script:
  #- mkdir -p ~/.ssh
  #- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  #- echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  #- chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $GITLAB_URL >> ~gitlab_ci_runner/.ssh/known_hosts


build:
  stage: build
  script:
    - apt-get -qq update
    - apt-get -y install build-essential cmake libeigen3-dev libboost-all-dev libgflags-dev git
    - cd /builds/penasa/spc
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ../
    - make -j 4
    
